# -*- coding: utf-8 -*-
"""
PDF qualitative + analytic report, assembled by the orchestrator AFTER the
adversarial game finishes. It embeds:
  - the LLM-written qualitative analysis (no template fallback when required),
  - the fairness metrics table (P-rule / DP / EoDD / EoOpp, before -> after),
  - every report chart (distributions, before/after, equalized odds).

Built with matplotlib's PdfPages, so it needs no extra dependency. Charts can be
added simply by appending to report["plots"].
"""
import os
import textwrap
import datetime
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.image as mpimg

A4P = (8.27, 11.69)     # portrait
A4L = (11.69, 8.27)     # landscape


def _wrap(text, width=98):
    out = []
    for para in (text or "").split("\n"):
        out.extend(textwrap.wrap(para, width=width) or [""])
    return out


def _text_pages(pdf, lines, title=None):
    """Render wrapped text across as many A4 pages as needed."""
    fig = plt.figure(figsize=A4P); ax = fig.add_axes([0, 0, 1, 1]); ax.axis("off")
    y = 0.95
    if title:
        ax.text(0.07, y, title, fontsize=16, fontweight="bold", va="top"); y -= 0.045
    for ln in lines:
        ax.text(0.07, y, ln, fontsize=10.5, va="top"); y -= 0.0235
        if y < 0.06:
            pdf.savefig(fig); plt.close(fig)
            fig = plt.figure(figsize=A4P); ax = fig.add_axes([0, 0, 1, 1]); ax.axis("off"); y = 0.95
    pdf.savefig(fig); plt.close(fig)


def generate_pdf_report(report: dict, out_dir: str, dataset_name: str,
                        pkg_dir: str = None, llm_model: str = None) -> str:
    """Write report_<dataset>.pdf into out_dir and return its path."""
    pkg_dir = pkg_dir or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.makedirs(out_dir, exist_ok=True)
    safe = (dataset_name or "run").replace(os.sep, "_")
    path = os.path.join(out_dir, f"report_{safe}.pdf")

    summary   = report.get("summary", {}) or {}
    fairness  = report.get("fairness", {}) or {}
    narrative = report.get("narrative", "") or ""
    plots     = report.get("plots", []) or []

    with PdfPages(path) as pdf:
        # ---- title page ----
        fig = plt.figure(figsize=A4P); ax = fig.add_axes([0, 0, 1, 1]); ax.axis("off")
        ax.text(0.5, 0.80, "Adversarial Fairness", fontsize=27, fontweight="bold", ha="center")
        ax.text(0.5, 0.745, "Qualitative & Analytic Report", fontsize=16, ha="center", color="#444")
        ax.text(0.5, 0.655, f"Dataset: {dataset_name}", fontsize=14, ha="center")
        ax.text(0.5, 0.615, datetime.date.today().isoformat(), fontsize=11, ha="center", color="#666")
        s = []
        if summary.get("acc_before") is not None:
            s.append(f"Accuracy:  {summary['acc_before']:.1f}%   ->   {summary.get('acc_after', 0):.1f}%")
        if summary.get("iterations") is not None:
            s.append(f"Iterations: {summary['iterations']}")
        for a, v in (summary.get("verdicts", {}) or {}).items():
            s.append(f"{a}:  {v}")
        ax.text(0.5, 0.50, "\n".join(s), fontsize=12, ha="center", va="top")
        if llm_model:
            ax.text(0.5, 0.05, f"Qualitative analysis generated by LLM: {llm_model}",
                    fontsize=9.5, ha="center", color="#888")
        pdf.savefig(fig); plt.close(fig)

        # ---- LLM narrative ----
        _text_pages(pdf, _wrap(narrative), title="Qualitative analysis (LLM)")

        # ---- fairness metrics table ----
        if fairness:
            fig = plt.figure(figsize=A4P); ax = fig.add_axes([0.05, 0.12, 0.9, 0.76]); ax.axis("off")
            ax.set_title("Fairness metrics  (before -> after)", fontsize=14, loc="left")
            cols = ["attribute", "P-rule", "DP", "EoDD", "EoOpp"]

            def ba(f, k):
                b, a = f.get(k + "_before"), f.get(k + "_after")
                return f"{b:.1f} -> {a:.1f}" if (b is not None and a is not None) else "-"
            rows = [[a, ba(f, "prule"), ba(f, "dp"), ba(f, "eodd"), ba(f, "eopp")]
                    for a, f in fairness.items()]
            t = ax.table(cellText=rows, colLabels=cols, loc="upper center", cellLoc="center")
            t.auto_set_font_size(False); t.set_fontsize(10.5); t.scale(1, 1.7)
            ax.text(0, -0.02, "P-rule higher is fairer; DP / EoDD / EoOpp lower is fairer.",
                    transform=ax.transAxes, fontsize=8.5, color="#777")
            pdf.savefig(fig); plt.close(fig)

        # ---- chart pages ----
        for p in plots:
            rel = p.get("plot"); title = p.get("title", "")
            img = os.path.join(pkg_dir, rel) if rel else None
            if img and os.path.exists(img):
                fig = plt.figure(figsize=A4L); ax = fig.add_axes([0.03, 0.04, 0.94, 0.88]); ax.axis("off")
                ax.set_title(title, fontsize=13)
                ax.imshow(mpimg.imread(img))
                pdf.savefig(fig); plt.close(fig)

    return path
